# Generated by Django 3.1.5 on 2021-01-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_auto_20210110_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='To continue click the link above...', max_length=255),
        ),
    ]
